### ISSUE TITLE
Product Mode

### ISSUE THREAD

**Issue by ibrahim-1702** [ibrahim-1702/SimpleBillingSystem#1]
The user should able to add a product into the file system,
The name of the file should be the product_Id 
File Contents:
      1) Name
      2) Price.
      3)Discount per pice.
      4)Taxes Applied.
The file contents should be entered by the user through intractive mode.

**Comment by rootanand** [comment]
For the classes, think again, carefully. Remember the methods belong to the class where the data resides. So separating the functionality like arithmetic and messages doesn't make sense. It has to be encapsulated in the class where it belongs.
